# Generated by Django 3.2.16 on 2022-11-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('swedish', 'Swedish'), ('dutch', 'Dutch'), ('portuguese', 'Portuguese'), ('mandarin', 'Mandarin'), ('hindi', 'Hindi '), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('russian', 'Russian')], default='1', max_length=12)),
                ('age', models.CharField(choices=[('4-7', '4-7'), ('7-11', '7-11'), ('11-13', '11-13'), ('14-17', '14-17'), ('18+', '18+')], max_length=8)),
                ('level', models.CharField(choices=[('beginners', 'Beginners'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(blank=True, upload_to='uploads/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
