# Generated by Django 3.2.16 on 2022-12-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.CharField(blank=True, choices=[('4-7', '4-7'), ('7-11', '7-11'), ('11-13', '11-13'), ('14-17', '14-17'), ('18+', '18+')], max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(blank=True, choices=[('beginners', 'Beginners'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50),
        ),
    ]
