# Generated by Django 3.2.16 on 2022-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221204_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.CharField(choices=[('4-7', '4-7'), ('7-11', '7-11'), ('11-13', '11-13'), ('14-17', '14-17'), ('18+', '18+')], default='4-7', max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Swedish', 'Swedish'), ('Dutch', 'Dutch'), ('Portuguese', 'Portuguese'), ('Mandarin', 'Mandarin'), ('Hindi', 'Hindi '), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Russian', 'Russian')], default='English', max_length=12),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('beginners', 'Beginners'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginners', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
