# Generated by Django 3.2.16 on 2022-11-28 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('swedish', 'Swedish'), ('dutch', 'Dutch'), ('portuguese', 'Portuguese'), ('mandarin', 'Mandarin'), ('hindi', 'Hindi ')], default='1', max_length=12)),
                ('language2', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('swedish', 'Swedish'), ('dutch', 'Dutch'), ('portuguese', 'Portuguese'), ('mandarin', 'Mandarin'), ('hindi', 'Hindi ')], default='1', max_length=12)),
                ('language3', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('swedish', 'Swedish'), ('dutch', 'Dutch'), ('portuguese', 'Portuguese'), ('mandarin', 'Mandarin'), ('hindi', 'Hindi ')], default='1', max_length=12)),
                ('about_me', models.TextField(blank=True, max_length=600)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
