# Generated by Django 3.2.16 on 2022-11-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
    ]
