# Generated by Django 3.2.16 on 2022-12-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_description'),
        ('saved_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SavedPosts', to='posts.post'),
        ),
    ]
