# Generated by Django 3.2.16 on 2022-12-04 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(4, 'excellent'), (3, 'very good'), (2, 'good'), (1, 'bad')])),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'post')},
            },
        ),
    ]
